version: '3.8'
services:
  matchy-service:
    build: ./profile_project_service    # 👈 pointe vers le bon dossier
    ports:
       - "8082:8082"  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/matchy_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=matchy_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs

volumes:
  mysql_data:
  sonar_data:
  sonar_logs: