apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: devops-microservices
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
