apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: devops-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: salmahaouarii/discovery-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
