apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: devops-microservices
spec:
  selector:
    app: discovery-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30761
  type: NodePort
