apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchy-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchy-frontend
  template:
    metadata:
      labels:
        app: matchy-frontend
    spec:
      containers:
      - name: matchy-frontend
        image: raouaaa/matchy-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: matchy-frontend
spec:
  selector:
    app: matchy-frontend
  ports:
  - port: 4200
    targetPort: 80
  type: LoadBalancer