spring.datasource.url=jdbc:mysql://localhost:3306/marketplace_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8085

# Eureka
spring.application.name=chat-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

jwt.secret=mySecretKeyForJWTTokenGenerationThatIsVeryLongAndSecure2024
jwt.expiration=86400000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Local file storage
app.upload.dir=uploads
app.upload.base-url=http://localhost:8085

logging.level.com.marketplace=DEBUG

# Jackson — dates as ISO strings, not timestamps
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# ZegoCloud Video Conference
zegocloud.app-id=856544200
zegocloud.app-sign=134c16c63ac6fa686259728436ef30a26c2dfd090913a2d4c17e8697c95bf018
zegocloud.server-secret=e69581cf9e48b90cacc8efc0b0c93f02
app.base-url=http://localhost:4200

# Traduction: LibreTranslate (instance publique) + MyMemory fallback
libretranslate.url=https://translate.argosopentech.com
libretranslate.api-key=

# Transcription: Groq Whisper (OpenAI-compatible)
whisper.url=https://api.groq.com/openai/v1/audio/transcriptions

groq.api-key=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


# HuggingFace — clé vide = fallback extractif local utilisé à la place
huggingface.api-key=

# distilbart pour le résumé IA (fallback local si indisponible)
#bart.url=https://api-inference.huggingface.co/models/sshleifer/distilbart-cnn-12-6

# Email (Gmail SMTP) — for meeting reminders
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=salmahaouari6@gmail.com
spring.mail.password=zyjuhgenzispcdzv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

