name: CI/CD Matchy - Profile Service

on:
  push:
    branches: [user-and-project-management]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: |
          cd profile_project_service
          mvn clean package -DskipTests

      - name: Run Unit Tests
        run: |
          cd profile_project_service
          mvn test -Dtest="MatchingServiceTest"

      - name: SonarCloud Analysis
        run: |
          cd profile_project_service
          mvn sonar:sonar \
            -Dsonar.projectKey=Esprit-PIDEV-4SAE7-2026-Matchy \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image
        run: docker build -t matchy-profile-service ./profile_project_service